#ifndef SCIFIR_BIOLOGY_GENES_COLLECTION_GENE_INFO_COLLECTION_SOURCE_HPP_INCLUDED
#define SCIFIR_BIOLOGY_GENES_COLLECTION_GENE_INFO_COLLECTION_SOURCE_HPP_INCLUDED

using namespace std;

namespace scifir
{
	class gene_info_collection_source
	{
		public:
			gene_info_collection_source();
	};
}

#endif // SCIFIR_BIOLOGY_GENES_COLLECTION_GENE_INFO_COLLECTION_SOURCE_HPP_INCLUDED

